In [ ]:
import os
import requests

if not os.path.exists("the-verdict.txt"):
  url = (
      "https://raw.githubusercontent.com/rasbt/"
      "LLMs-from-scratch/main/ch02/01_main-chapter-code/"
      "the-verdict.txt"
  )
  file_path = "the-verdict.txt"

  response = requests.get(url, timeout=30)
  response.raise_for_status()
  with open(file_path, "wb") as f:
    f.write(response.content)

In [ ]:
with open(file_path, "r", encoding="utf-8") as f:
  raw_text = f.read()

In [ ]:
print("Total length the text: ", len(raw_text))

Total length the text:  20479


In [ ]:
print(raw_text[:100])

I HAD always thought Jack Gisburn rather a cheap genius--though a good fellow enough--so it was no g


In [ ]:
import re
text = "Hello, world. This, is a test."


In [ ]:
result = re.split(" ",  text)
result

['Hello,', 'world.', 'This,', 'is', 'a', 'test.']

In [ ]:
result = re.split(r"\s", text)
result

['Hello,', 'world.', 'This,', 'is', 'a', 'test.']

In [ ]:
result = re.split(r"(\s)", text)
result

['Hello,', ' ', 'world.', ' ', 'This,', ' ', 'is', ' ', 'a', ' ', 'test.']

In [ ]:
result = re.split(r"[,.]",text)
result

['Hello', ' world', ' This', ' is a test', '']

In [ ]:
result = re.split(r"([.,]|s)", text)
result

['Hello',
 ',',
 ' world',
 '.',
 ' Thi',
 's',
 '',
 ',',
 ' i',
 's',
 ' a te',
 's',
 't',
 '.',
 '']

In [ ]:
result = [r for r in result]
result


['Hello',
 ',',
 ' world',
 '.',
 ' Thi',
 's',
 '',
 ',',
 ' i',
 's',
 ' a te',
 's',
 't',
 '.',
 '']

In [ ]:
result = [r for r in result if r.strip()]
result

['Hello',
 ',',
 ' world',
 '.',
 ' Thi',
 's',
 ',',
 ' i',
 's',
 ' a te',
 's',
 't',
 '.']

In [ ]:
text = "Hello, world. Is this-- a test?"
result = re.split(r'([,._:;?!"()\']|--|\s)', text)
result = [item for item in result if item.strip()]
result

['Hello', ',', 'world', '.', 'Is', 'this', '--', 'a', 'test', '?']

In [ ]:
preprocessed = re.split(r'([,._:;?!"()\']|--|\s)', raw_text)
preprocessed = [item for item in preprocessed if item.strip()]
preprocessed[:30]

['I',
 'HAD',
 'always',
 'thought',
 'Jack',
 'Gisburn',
 'rather',
 'a',
 'cheap',
 'genius',
 '--',
 'though',
 'a',
 'good',
 'fellow',
 'enough',
 '--',
 'so',
 'it',
 'was',
 'no',
 'great',
 'surprise',
 'to',
 'me',
 'to',
 'hear',
 'that',
 ',',
 'in']

In [ ]:
len(preprocessed)

4690

In [ ]:
all_words = sorted(set(preprocessed))
vocab_size = len(all_words)
vocab_size

1130

In [ ]:
vocab = {token: integer for integer, token in enumerate(all_words)}
for i, item in enumerate(vocab.items()):
  print(item)
  if i >= 50:
    break

('!', 0)
('"', 1)
("'", 2)
('(', 3)
(')', 4)
(',', 5)
('--', 6)
('.', 7)
(':', 8)
(';', 9)
('?', 10)
('A', 11)
('Ah', 12)
('Among', 13)
('And', 14)
('Are', 15)
('Arrt', 16)
('As', 17)
('At', 18)
('Be', 19)
('Begin', 20)
('Burlington', 21)
('But', 22)
('By', 23)
('Carlo', 24)
('Chicago', 25)
('Claude', 26)
('Come', 27)
('Croft', 28)
('Destroyed', 29)
('Devonshire', 30)
('Don', 31)
('Dubarry', 32)
('Emperors', 33)
('Florence', 34)
('For', 35)
('Gallery', 36)
('Gideon', 37)
('Gisburn', 38)
('Gisburns', 39)
('Grafton', 40)
('Greek', 41)
('Grindle', 42)
('Grindles', 43)
('HAD', 44)
('Had', 45)
('Hang', 46)
('Has', 47)
('He', 48)
('Her', 49)
('Hermia', 50)


In [ ]:
for k, v in vocab.items():
  print(f"{k} : {v}")
  if v >= 50:
    break

! : 0
" : 1
' : 2
( : 3
) : 4
, : 5
-- : 6
. : 7
: : 8
; : 9
? : 10
A : 11
Ah : 12
Among : 13
And : 14
Are : 15
Arrt : 16
As : 17
At : 18
Be : 19
Begin : 20
Burlington : 21
But : 22
By : 23
Carlo : 24
Chicago : 25
Claude : 26
Come : 27
Croft : 28
Destroyed : 29
Devonshire : 30
Don : 31
Dubarry : 32
Emperors : 33
Florence : 34
For : 35
Gallery : 36
Gideon : 37
Gisburn : 38
Gisburns : 39
Grafton : 40
Greek : 41
Grindle : 42
Grindles : 43
HAD : 44
Had : 45
Hang : 46
Has : 47
He : 48
Her : 49
Hermia : 50


In [ ]:
class SimpleTokenizerV1:
  def __init__(self, vocab):
    self.str_to_int = vocab
    self.int_to_str = {i: s for s, i in vocab.items()}

  def encode(self, text):
    preprocessed = re.split(r'([,.?_!"()\']|--|\s)', text)
    preprocessed = [
        item.strip() for item in preprocessed if item.strip()
    ]
    ids = [self.str_to_int[i] for i in preprocessed]
    return ids

  def decode(self, ids):
    text = " ".join([self.int_to_str[i] for i in ids])
    text = re.sub(r'\s+([,.?!"()\'])', r'\1', text)
    return text



In [ ]:
tokenizer = SimpleTokenizerV1(vocab)
text = """"It's the last he painted, you know,"
Mrs. Gisburn said with pardonable pride."""
ids = tokenizer.encode(text)
ids

[1,
 56,
 2,
 850,
 988,
 602,
 533,
 746,
 5,
 1126,
 596,
 5,
 1,
 67,
 7,
 38,
 851,
 1108,
 754,
 793,
 7]

In [ ]:
textrecover = tokenizer.decode(ids)
textrecover

'" It\' s the last he painted, you know," Mrs. Gisburn said with pardonable pride.'

In [ ]:
all_tokens = sorted(list(set(preprocessed)))
all_tokens[-5:]

['yet', 'you', 'younger', 'your', 'yourself']

In [ ]:
leng = len(all_tokens)
leng

1130

In [ ]:
all_tokens.extend(["<|endoftext|>", "<|unk|>"])
leng = len(all_tokens)
leng

1132

In [ ]:
vocab = {token: integer for integer, token in enumerate(all_tokens)}
print(len(vocab))

1132


In [ ]:
print(len(vocab.items()))

1132


In [ ]:
for i,  item in enumerate(list(vocab.items())[-4:]):
  print(item)

('your', 1128)
('yourself', 1129)
('<|endoftext|>', 1130)
('<|unk|>', 1131)


In [ ]:
for i in vocab.items():
  print(i)

('!', 0)
('"', 1)
("'", 2)
('(', 3)
(')', 4)
(',', 5)
('--', 6)
('.', 7)
(':', 8)
(';', 9)
('?', 10)
('A', 11)
('Ah', 12)
('Among', 13)
('And', 14)
('Are', 15)
('Arrt', 16)
('As', 17)
('At', 18)
('Be', 19)
('Begin', 20)
('Burlington', 21)
('But', 22)
('By', 23)
('Carlo', 24)
('Chicago', 25)
('Claude', 26)
('Come', 27)
('Croft', 28)
('Destroyed', 29)
('Devonshire', 30)
('Don', 31)
('Dubarry', 32)
('Emperors', 33)
('Florence', 34)
('For', 35)
('Gallery', 36)
('Gideon', 37)
('Gisburn', 38)
('Gisburns', 39)
('Grafton', 40)
('Greek', 41)
('Grindle', 42)
('Grindles', 43)
('HAD', 44)
('Had', 45)
('Hang', 46)
('Has', 47)
('He', 48)
('Her', 49)
('Hermia', 50)
('His', 51)
('How', 52)
('I', 53)
('If', 54)
('In', 55)
('It', 56)
('Jack', 57)
('Jove', 58)
('Just', 59)
('Lord', 60)
('Made', 61)
('Miss', 62)
('Money', 63)
('Monte', 64)
('Moon-dancers', 65)
('Mr', 66)
('Mrs', 67)
('My', 68)
('Never', 69)
('No', 70)
('Now', 71)
('Nutley', 72)
('Of', 73)
('Oh', 74)
('On', 75)
('Once', 76)
('Only', 77)
('

In [ ]:
class SimpleTokenizerV2:
  def __init__(self,  vocab):
    self.str_to_int = vocab
    self.int_to_str = {i: s for s, i in vocab.items()}

  def encode(self, text):
    preprocessed = re.split(r'([,.:.?_!"()\']|--|\s)', text)
    preprocessed = [
        item.strip() for item in preprocessed if item.strip()
    ]
    preprocessed = [item if item in self.str_to_int else "<|unk|>"
                    for item in preprocessed]
    ids = [self.str_to_int[i] for i in preprocessed]
    return ids

  def decode(self, ids):
    text =" ".join([self.int_to_str[i] for i in ids])
    text = re.sub(r'\s+([.;,:?!()\'])',r'\1', text)
    return text



In [ ]:
text1 = "Hello, do you like tea?"
text2 = "In the sunlit terraces of the palace."
text = " <|endoftext|> ".join((text1, text2))
print(type(text))

<class 'str'>


In [ ]:
text

'Hello, do you like tea? <|endoftext|> In the sunlit terraces of the palace.'

In [ ]:
tokenizer = SimpleTokenizerV2(vocab)
ids = tokenizer.encode(text)
ids

[1131, 5, 355, 1126, 628, 975, 10, 1130, 55, 988, 956, 984, 722, 988, 1131, 7]

In [ ]:
textrecover = tokenizer.decode(ids)
textrecover

'<|unk|>, do you like tea? <|endoftext|> In the sunlit terraces of the <|unk|>.'

In [ ]:
!pip install tiktoken

In [ ]:
from importlib.metadata import  version
import tiktoken
version("tiktoken")

'0.12.0'

In [ ]:
tiktoken.__version__

'0.12.0'

In [ ]:
tokenizer = tiktoken.get_encoding("gpt2")


In [ ]:
text = (
"Hello, do you like tea? <|endoftext|> In the sunlit terraces"
"of someunknownPlace."
)

In [ ]:
ids = tokenizer.encode(text, allowed_special={"<|endoftext|>"})
ids

[15496,
 11,
 466,
 345,
 588,
 8887,
 30,
 220,
 50256,
 554,
 262,
 4252,
 18250,
 8812,
 2114,
 1659,
 617,
 34680,
 27271,
 13]

In [ ]:
strings = tokenizer.decode(ids)
strings

'Hello, do you like tea? <|endoftext|> In the sunlit terracesof someunknownPlace.'

In [ ]:
len(text), len(ids)

(80, 20)

In [ ]:
text_list = text.split(" ")

In [ ]:
len(text_list)

11

In [ ]:
with open("the-verdict.txt", "r", encoding="utf-8") as f:
  raw_text = f.read()

enc_text = tokenizer.encode(raw_text)
len(enc_text)

5145

In [ ]:
enc_sample = enc_text[:50]
context_size = 4
x = enc_sample[:context_size]
y = enc_sample[1: context_size + 1]
x,  y

([40, 367, 2885, 1464], [367, 2885, 1464, 1807])

In [ ]:
for i in range(1, context_size + 1):
  context = enc_sample[:i]
  desired = enc_sample[i]
  print(context, "----->", desired)
  print(tokenizer.decode(context), "----->", tokenizer.decode([desired]))

[40] -----> 367
I ----->  H
[40, 367] -----> 2885
I H -----> AD
[40, 367, 2885] -----> 1464
I HAD ----->  always
[40, 367, 2885, 1464] -----> 1807
I HAD always ----->  thought


In [ ]:
import torch
torch.__version__

'2.10.0+cpu'

In [ ]:
from torch.utils.data import Dataset, DataLoader

In [ ]:
class GPTDatasetV1(Dataset):
  def __init__(self, txt, tokenizer, max_length, stride):
    self.input_ids = []
    self.target_ids = []
    token_ids = tokenizer.encode(txt, allowed_special={"<|endoftext|>"})
    assert len(token_ids) > max_length, "number of tokens is too short"

    for i in range(0, len(token_ids) - max_length,  stride):
      input_chunk = token_ids[i: i + max_length]
      target_chunk = token_ids[i +1: i + max_length + 1]
      self.input_ids.append(torch.tensor(input_chunk, dtype=torch.long))
      self.target_ids.append(torch.tensor(target_chunk, dtype=torch.long))

  def __len__(self):
    return len(self.input_ids)

  def __getitem__(self, idx):
    return self.input_ids[idx], self.target_ids[idx]


In [ ]:

class GPTDatasetV1(Dataset):
    def __init__(self, txt, tokenizer, max_length, stride):
        self.input_ids = []
        self.target_ids = []

        # Tokenize the entire text
        token_ids = tokenizer.encode(txt, allowed_special={"<|endoftext|>"})
        assert len(token_ids) > max_length, "Number of tokenized inputs must at least be equal to max_length+1"

        # Use a sliding window to chunk the book into overlapping sequences of max_length
        for i in range(0, len(token_ids) - max_length, stride):
            input_chunk = token_ids[i:i + max_length]
            target_chunk = token_ids[i + 1: i + max_length + 1]
            self.input_ids.append(torch.tensor(input_chunk))
            self.target_ids.append(torch.tensor(target_chunk))

    def __len__(self):
        return len(self.input_ids)

    def __getitem__(self, idx):
        return self.input_ids[idx], self.target_ids[idx]

In [ ]:
def create_dataloader_v1(txt, batch_size=4,  max_length=256, stride=128, shuffle=True,
                         drop_last=True, num_workers=0):
  tokenizer = tiktoken.get_encoding("gpt2")
  dataset = GPTDatasetV1(txt, tokenizer, max_length, stride)

  dataloader = DataLoader(dataset,
                          batch_size=batch_size,
                          shuffle=shuffle,
                          drop_last=drop_last,
                          num_workers=num_workers)
  return dataloader

In [ ]:
with open("the-verdict.txt", "r", encoding="utf-8") as f:
  raw_text = f.read()

In [ ]:
dataloader = create_dataloader_v1(
    raw_text, batch_size=1, max_length=4, stride=1, shuffle=False
)
data_iter = iter(dataloader)
first_batch = next(data_iter)
first_batch

[tensor([[  40,  367, 2885, 1464]]), tensor([[ 367, 2885, 1464, 1807]])]

In [ ]:
second_batch = next(data_iter)

In [ ]:
second_batch

[tensor([[ 367, 2885, 1464, 1807]]), tensor([[2885, 1464, 1807, 3619]])]

In [ ]:
dataloader = create_dataloader_v1(raw_text, batch_size=8, max_length=4, stride=1)
data_iter = iter(dataloader)
first_batch = next(data_iter)
first_batch

[tensor([[ 7454,    11,   618,   314],
         [  565,   418,  1039,    11],
         [   30,  4162,    11,   314],
         [  284,  7808,   607, 10927],
         [  887,   673,  3521,   470],
         [  373,   257, 17548,   286],
         [ 2106,    13,  1375,  4762],
         [  287,   465,  2951,    13]]),
 tensor([[   11,   618,   314,  3114],
         [  418,  1039,    11,   262],
         [ 4162,    11,   314,   550],
         [ 7808,   607, 10927,  1108],
         [  673,  3521,   470,  6842],
         [  257, 17548,   286,   257],
         [   13,  1375,  4762,   287],
         [  465,  2951,    13,   198]])]

In [ ]:
input_ids = torch.tensor([2, 3, 5, 1])

In [ ]:
input_ids

tensor([2, 3, 5, 1])

In [ ]:
vocab_size = 6
output_dim = 3
torch.manual_seed(123)
embedding_layer = torch.nn.Embedding(vocab_size, output_dim)

In [ ]:
embedding_layer.weight

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.1690],
        [ 0.9178,  1.5810,  1.3010],
        [ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-1.1589,  0.3255, -0.6315],
        [-2.8400, -0.7849, -1.4096]], requires_grad=True)

In [ ]:
embedding_layer(torch.tensor([3]))

tensor([[-0.4015,  0.9666, -1.1481]], grad_fn=<EmbeddingBackward0>)

In [ ]:
embedding_layer(input_ids)

tensor([[ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-2.8400, -0.7849, -1.4096],
        [ 0.9178,  1.5810,  1.3010]], grad_fn=<EmbeddingBackward0>)

In [ ]:
vocab_size = 50257
output_dim = 256
token_embedding_layer = torch.nn.Embedding(vocab_size, output_dim)


In [ ]:
max_length = 4
dataloader = create_dataloader_v1(
    raw_text, batch_size=8, max_length=max_length,
    stride=max_length, shuffle=False
)

In [ ]:
data_iter = iter(dataloader)
inputs, tartets = next(data_iter)
inputs

tensor([[   40,   367,  2885,  1464],
        [ 1807,  3619,   402,   271],
        [10899,  2138,   257,  7026],
        [15632,   438,  2016,   257],
        [  922,  5891,  1576,   438],
        [  568,   340,   373,   645],
        [ 1049,  5975,   284,   502],
        [  284,  3285,   326,    11]])

In [ ]:
inputs.shape

torch.Size([8, 4])

In [ ]:
token_embeddings = token_embedding_layer(inputs)
token_embeddings.shape

torch.Size([8, 4, 256])

In [ ]:
context_length = max_length
pos_embedding_layer = torch.nn.Embedding(context_length, output_dim)
pos_embeddings = pos_embedding_layer(torch.arange(max_length))
pos_embeddings.shape

torch.Size([4, 256])

In [ ]:
input_embeddings = token_embeddings + pos_embeddings
input_embeddings.shape

torch.Size([8, 4, 256])

In [ ]:
input_embeddings[:3]

tensor([[[ 2.2288,  0.5619,  0.8286,  ..., -0.6272, -0.2987,  0.8900],
         [ 2.0903, -0.4664, -0.0593,  ...,  0.9115, -1.0493, -1.6473],
         [-0.7158, -0.8304,  1.2494,  ...,  2.3952,  1.8773,  0.8051],
         [ 0.2703,  0.4029,  3.0514,  ...,  0.3595, -1.4548,  0.8310]],

        [[ 3.2835,  1.1749, -1.4150,  ..., -0.3281,  2.4332,  0.6924],
         [-0.2199, -0.9114, -0.1750,  ...,  1.5337, -0.1998,  0.1462],
         [ 1.5197, -1.4240,  0.4391,  ...,  1.0494, -1.4318,  2.3057],
         [ 0.2893,  0.8346, -0.1884,  ...,  1.9602,  0.8709,  0.8796]],

        [[ 0.9662,  0.0952, -0.4640,  ..., -1.0320,  1.6290,  1.7771],
         [ 2.4468, -0.2154,  1.4984,  ...,  1.8766,  0.5595, -0.1423],
         [-0.3856, -2.5393,  1.1556,  ...,  3.6157,  1.3267,  0.4944],
         [-0.2487, -0.5275,  2.0009,  ...,  0.2930,  0.5977,  1.3300]]],
       grad_fn=<SliceBackward0>)